
module.exports = {
  chromeConfig: {
    devtools: false,
    ignoreHTTPSErrors: true,
    defaultViewport: null,
    // defaultViewport: {
    //   width: 1280,
    //   height: 800
    // },
    args: [
      '--disable-xss-auditor',
      '--ignore-certificate-errors',
      '--allow-running-insecure-content',
      // '--disable-web-security', // disabled
      '--disable-resize-lock',
      '--window-size=1280,800',
      '--no-sandbox'
    ]
  },

  adsBlackList: [
    'googletagmanager.com',
    'google-analytics.com',
    'googleadservices.com',
    'redditstatic.com',
    'ads-twitter.com',
    'facebook.net',
    'albacross.com',
    'google-analytics.com',
    'hs-analytics.net',
    'doubleclick.net',
    'analytics.twitter.com',
    'intercomcdn.com',
    'hs-scripts.com',
    'usemessages.com',
    'snap.licdn.com',
    'consensu.org',
    'gemius.pl',
    'pubstack.io',
    'bkrtx.com',
    'jsdelivr.net',
    'bluekai.com',
    'digitru.st',
    'rubiconproject.com',
    'criteo.net',
    'adnxs.com',
    'pub.web.sapo.io',
    'taboola.com',
    'hotjar.com',
    'scorecardresearch.com',
    'moatads.com',
    '2mdn.net',
    'adservice.google.pt',
    'adservice.google.com',
    'googletagservices.com',
    'navdmp.com',
    'googlesyndication.com',
    'facebook.com/plugins/like',
    'facebook.com/rsrc.php',
    'sdk.privacy-center.org',
    'amazon-adsystem.com',
    'outbrain.com',
    'onetrust.com',
    'cdn.cookielaw.org',
    'dynamicyield.com',
    'zdassets.com',
    'zendesk.com',
    'gstatic.com/recaptcha',
    'freshchat.com',
    'userguiding.com',
    'js.stripe.com',
    'hubspot.com',
    'm.stripe.network',
    'm.stripe.com',
    'intercom.io',
  ],

  reMatchPaths: {
    re: "[^/][`'\"]([\/][a-zA-Z0-9_.-]+)+(?!([gimuy]*[,;\s])|\/\2)",
    fileSufix: 'paths',
    clean: "^[^\/]+",
  },

};
